version: "3.9"
services:
  elasticsearch:
    image: elastic/elasticsearch:7.17.4
    ports:
      - 9201:9200
      - 9301:9300
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
  kibana:
    image: elastic/kibana:7.17.4
    environment:
      - I18N_LOCALE=zh-CN
    ports:
      - 5601:5601
  apm-server:
    image: elastic/apm-server:7.17.4
    environment:
      - output.elasticsearch.hosts=["elasticsearch:9200"]
